apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-web-app
  template:
    metadata:
      labels:
        app: capstone-web-app
    spec:
      containers:
        - name: web
          image: 463655182088.dkr.ecr.ap-south-1.amazonaws.com/capstone-web-app-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

