apiVersion: v1
kind: Service
metadata:
  name: capstone-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

